// src/library/infrastructure/primary/BookComponent.tsx
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { inject } from '@/injections.ts';
import { BOOKS } from '@/library/application/LibraryKeys.ts';
import { Book } from '@/library/domain/Book.ts';
import { ISBN } from '@/library/domain/ISBN.ts';
import { Loader, loadError, loadFor, loadInProgress, loadSuccess } from '@/library/infrastructure/primary/Loader.ts';

const BookInfoComponent = ({ book }: { book: Book }) => {
  const { t } = useTranslation();
  return (
    <ul>
      <li data-selector="book.title">
        <strong data-selector="book.label.title">{t('book.title')} </strong>
        <span data-selector="book.title">{book.title}</span>
      </li>
      <li data-selector="book.isbn">{book.isbn.get()}</li>
    </ul>
  );
};

export const BookComponent = (props: { isbn: ISBN }) => {
  const { t } = useTranslation();
  const [bookLoader, setBookLoader] = useState<Loader<Book>>(loadInProgress());

  useEffect(() => {
    setBookLoader(loadInProgress());
    inject(BOOKS)
      .get(props.isbn)
      .then(either =>
        either.evaluate(
          error => setBookLoader(loadError(error.message)),
          content => setBookLoader(loadSuccess(content))
        )
      )
      .catch((error: Error) => setBookLoader(loadError(error.message)));
  }, [props.isbn]);

  return loadFor(bookLoader)({
    progress: () => <p data-selector="book.loading">{t('book.inProgress')}</p>,
    error: message => <p data-selector="book.error">{message}</p>,
    success: book => <BookInfoComponent book={book} />,
  });
};

// src/library/infrastructure/primary/BookComponent.svelte
<script lang="ts">
  import {ISBN} from "@/library/domain/ISBN.ts";
  import {inject} from "@/injections.ts";
  import {BOOKS} from "@/library/application/LibraryKeys.ts";
  import {
    type Loader,
    loadError, LoadingError,
    LoadingInProgress, LoadingSuccess,
    loadInProgress,
    loadSuccess
  } from "@/library/infrastructure/primary/Loader.ts";
  import type {Book} from "@/library/domain/Book.ts";
  import BookInfoComponent from "@/library/infrastructure/primary/BookInfoComponent.svelte";
  import i18nextSvelte from "@/i18next-svelte.ts";

  export let isbn: ISBN;

  let bookLoader: Loader<Book> = loadInProgress();

  inject(BOOKS)
    .get(isbn)
    .then(either => {
      either.evaluate(
        error => bookLoader = loadError(error.message),
        content => bookLoader = loadSuccess(content),
      )
    })
    .catch((error: Error) => bookLoader = loadError(error.message));
</script>

{#if (bookLoader.status === LoadingInProgress)}
  <p data-selector="book.loading">{$i18nextSvelte.t('book.inProgress')}</p>
{/if}

{#if (bookLoader.status === LoadingError)}
  <p data-selector="book.error">{bookLoader.errorMessage}</p>
{/if}

{#if (bookLoader.status === LoadingSuccess)}
  <BookInfoComponent book="{bookLoader.content}" />
{/if}
