// src/library/infrastructure/primary/Book.tsx
import { useState } from 'react';
import { useLoadEither } from '@/library/infrastructure/primary/UseLoad';
import { useTranslation } from 'react-i18next';
import { inject } from '@/injections.ts';
import { BOOKS } from '@/library/application/LibraryKeys.ts';

export const Book = () => {
  const books = inject(BOOKS);

  const {t} = useTranslation();
  const [title, setTitle] = useState('');
  const [isbn, setISBN] = useState('');

  const {isInProgress, isFailing, isSuccessful, errorMessage} = useLoadEither(books.get(), book => {
    setTitle(book.title);
    setISBN(book.isbn.get());
  });

  return (
    <>
      { isInProgress &&
        <p data-selector="book.loading">{t('book.inProgress')}</p>
      }
      { isFailing &&
        <p data-selector="book.error">{errorMessage}</p>
      }
      { isSuccessful &&
        <ul>
          <li data-selector="book.title">
              <strong data-selector="book.label.title">{t('book.title')} </strong>
              <span data-selector="book.title">{title}</span>
          </li>
          <li data-selector="book.isbn">{isbn}</li>
        </ul>
      }
    </>
  )
};

// src/library/infrastructure/primary/BookComponent.svelte
<script lang="ts">
  import {ISBN} from "@/library/domain/ISBN.ts";
  import {inject} from "@/injections.ts";
  import {BOOKS} from "@/library/application/LibraryKeys.ts";
  import {
    type Loader,
    loadError, LoadingError,
    LoadingInProgress, LoadingSuccess,
    loadInProgress,
    loadSuccess
  } from "@/library/infrastructure/primary/Loader.ts";
  import type {Book} from "@/library/domain/Book.ts";
  import BookInfoComponent from "@/library/infrastructure/primary/BookInfoComponent.svelte";
  import i18nextSvelte from "@/i18next-svelte.ts";

  export let isbn: ISBN;

  let bookLoader: Loader<Book> = loadInProgress();

  inject(BOOKS)
    .get(isbn)
    .then(either => {
      either.evaluate(
        error => bookLoader = loadError(error.message),
        content => bookLoader = loadSuccess(content),
      )
    })
    .catch((error: Error) => bookLoader = loadError(error.message));
</script>

{#if (bookLoader.status === LoadingInProgress)}
  <p data-selector="book.loading">{$i18nextSvelte.t('book.inProgress')}</p>
{/if}

{#if (bookLoader.status === LoadingError)}
  <p data-selector="book.error">{bookLoader.errorMessage}</p>
{/if}

{#if (bookLoader.status === LoadingSuccess)}
  <BookInfoComponent book="{bookLoader.content}" />
{/if}
