// src/library/infrastructure/primary/BookComponent.svelte
<script lang="ts">
  import {ISBN} from "@/library/domain/ISBN.ts";
  import {inject} from "@/injections.ts";
  import {BOOKS} from "@/library/application/LibraryKeys.ts";
  import {
    type Loader,
    loadError, LoadingError,
    LoadingInProgress, LoadingSuccess,
    loadInProgress,
    loadSuccess
  } from "@/library/infrastructure/primary/Loader.ts";
  import type {Book} from "@/library/domain/Book.ts";
  import BookInfoComponent from "@/library/infrastructure/primary/BookInfoComponent.svelte";
  import i18nextSvelte from "@/i18next-svelte.ts";

  export let isbn: ISBN;

  let bookLoader: Loader<Book> = loadInProgress();

  inject(BOOKS)
    .get(isbn)
    .then(either => {
      either.evaluate(
        error => bookLoader = loadError(error.message),
        content => bookLoader = loadSuccess(content),
      )
    })
    .catch((error: Error) => bookLoader = loadError(error.message));
</script>

{#if (bookLoader.status === LoadingInProgress)}
  <p data-selector="book.loading">{$i18nextSvelte.t('book.inProgress')}</p>
{/if}

{#if (bookLoader.status === LoadingError)}
  <p data-selector="book.error">{bookLoader.errorMessage}</p>
{/if}

{#if (bookLoader.status === LoadingSuccess)}
  <BookInfoComponent book="{bookLoader.content}" />
{/if}

// src/library/infrastructure/primary/BookComponent.vue
<template>
  <p data-selector="book.loading" v-if="bookLoader.status === LoadingInProgress">{{t('book.inProgress')}}</p>
  <p data-selector="book.error" v-if="bookLoader.status === LoadingError">{{ (bookLoader as LoadError).errorMessage }}</p>
  <template v-if="bookLoader.status === LoadingSuccess"><BookInfoComponent :book="(bookLoader as LoadSuccess<Book>).content" /></template>
</template>

<script lang="ts">
import {defineComponent, PropType, ref} from "vue";
import {ISBN} from "@/library/domain/ISBN.ts";
import {inject} from "@/injections.ts";
import {BOOKS} from "@/library/application/LibraryKeys.ts";
import {
  Loader, LoadError,
  loadError, LoadingError,
  LoadingInProgress, LoadingSuccess,
  loadInProgress, LoadSuccess,
  loadSuccess
} from "@/library/infrastructure/primary/Loader.ts";
import {Book} from "@/library/domain/Book.ts";
import BookInfoComponent from "@/library/infrastructure/primary/BookInfoComponent.vue";
import {useTranslation} from "i18next-vue";

export default defineComponent({
  components: {BookInfoComponent},
  props: {
    isbn: {
      type: Object as PropType<ISBN>,
      required: true,
    },
  },
  setup(props) {
    const {t} = useTranslation();
    const bookLoader = ref<Loader<Book>>(loadInProgress())
    inject(BOOKS)
      .get(props.isbn)
      .then(either =>
        either.evaluate(
          error => bookLoader.value = loadError(error.message),
          content => bookLoader.value = loadSuccess(content),
        )
      )
      .catch((error: Error) => bookLoader.value = loadError(error.message));
    return {
      bookLoader,
      LoadingInProgress,
      LoadingError,
      LoadingSuccess,
      t,
    }
  }
})
</script>
